// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2876.Stronghold2016.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc2876.Stronghold2016.subsystems.*;

/**
 *
 */
public class AutoCGCrossCheval extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutoCGCrossCheval() {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

        // arm should be at top before we start crossing cheval. maybe
        // let drivers move it themselves?
        addSequential(new ArmToTop());

        // Robot should start pretty close to cheval ramp because we
        // are going to move the arm down as we try to drive up the
        // ramp.
        addSequential(new DriveUpRampStop(0, .5));
        addParallel(new ArmToBottom());

        // Now the robot should be on ramp with arm all the way
        // down. Should be good to drive over cheval.  I just picked
        // 60, no idea if it is too far
        addSequential(new AutoDriveDistance(60, .7));

    }
}
