// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2876.Stronghold2016.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;



import org.usfirst.frc2876.Stronghold2016.Robot;

/**
 *
 */
public class DriveCrossDefense extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_distance;
    private double m_speed;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    
    private boolean startCross;
    private boolean endCross;
    private boolean timerStarted;
    private Timer time = new Timer();
    private static final double SETTLE_TIME = .5;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveCrossDefense(double distance, double speed) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
//        m_distance = Math.abs(distance);
        m_speed = speed;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	startCross = false;
    	endCross = false;
    	timerStarted = false;
    	Robot.driveTrain.resetEncoders();
    	Robot.navX.zeroYaw();
    	Robot.driveTrain.turnController.setSetpoint(0);
    	Robot.driveTrain.turnController.enable();
    	time.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//This logic is questionable and could be simplified, but it works. If it ain't broke...
    	Robot.driveTrain.myRobot.arcadeDrive(m_speed, -Robot.driveTrain.turnController.get(), true);
    	if (!startCross){
    		startCross = Robot.driveTrain.isCrossingDefense();
    	} else {
    		boolean end = !Robot.driveTrain.isCrossingDefense();
    		if (end && !timerStarted) {
    			time.start();
    			timerStarted = true;
    		} else if(!end) {
    			time.reset();
    			time.stop();
    			timerStarted = false;
    		}
    		if(end && timerStarted && time.get() > SETTLE_TIME){
    			endCross = true;
    		}
    	}
//    	if (m_distance > 0 && m_distance < Math.abs(Robot.driveTrain.getDistance())) {
//    		endCross = true;
//    	}

    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return endCross;
    }

    // Called once after isFinished returns true
    protected void end() {
    	time.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
