// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2876.Stronghold2016;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogAccelerometer;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.CANTalon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainCANTalon1;
    public static CANTalon driveTrainCANTalon2;
    public static CANTalon driveTrainCANTalon3;
    public static CANTalon driveTrainCANTalon4;
    public static AnalogGyro driveTrainAnalogGyro1;
    public static AnalogAccelerometer driveTrainAnalogAccelerometer1;
    public static CANTalon shooterCANTalon1;
    public static CANTalon shooterCANTalon2;
    public static CANTalon shooterCANTalon3;
    public static CANTalon shooterCANTalon4;
    public static CANTalon armCANTalon1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainCANTalon1 = new CANTalon(0);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 1", driveTrainCANTalon1);
        
        driveTrainCANTalon2 = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 2", driveTrainCANTalon2);
        
        driveTrainCANTalon3 = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 3", driveTrainCANTalon3);
        
        driveTrainCANTalon4 = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 4", driveTrainCANTalon4);
        
        driveTrainAnalogGyro1 = new AnalogGyro(0);
        LiveWindow.addSensor("DriveTrain", "AnalogGyro 1", driveTrainAnalogGyro1);
        driveTrainAnalogGyro1.setSensitivity(0.007);
        driveTrainAnalogAccelerometer1 = new AnalogAccelerometer(1);
        LiveWindow.addSensor("DriveTrain", "AnalogAccelerometer 1", driveTrainAnalogAccelerometer1);
        driveTrainAnalogAccelerometer1.setSensitivity(0.0);
        driveTrainAnalogAccelerometer1.setZero(2.5);
        shooterCANTalon1 = new CANTalon(4);
        LiveWindow.addActuator("Shooter", "CAN Talon 1", shooterCANTalon1);
        
        shooterCANTalon2 = new CANTalon(5);
        LiveWindow.addActuator("Shooter", "CAN Talon 2", shooterCANTalon2);
        
        shooterCANTalon3 = new CANTalon(6);
        LiveWindow.addActuator("Shooter", "CAN Talon 3", shooterCANTalon3);
        
        shooterCANTalon4 = new CANTalon(7);
        LiveWindow.addActuator("Shooter", "CAN Talon 4", shooterCANTalon4);
        
        armCANTalon1 = new CANTalon(8);
        LiveWindow.addActuator("Arm", "CAN Talon 1", armCANTalon1);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
